development:
  adapter: postgresql
  database: vollot_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: vollot_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: vollot_production
  pool: 5
  timeout: 5000
